import csv
from EndCalculation import *


with open('/home/andrej/Documents/induction-motor-design-tool/designed_motor_parameters/Parameters.csv', 'w', newline='') as csvfile:
    fieldnames = ['Name of Parameter', 'Value']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()
    writer.writerow({'Name of Parameter': 'Pn', 'Value': P_2n})
    writer.writerow({'Name of Parameter': 'Un', 'Value': Un})
    writer.writerow({'Name of Parameter': 'Winding Connection', 'Value': Scheme_Stator})
    writer.writerow({'Name of Parameter': 'f', 'Value': f})
    writer.writerow({'Name of Parameter': 'eta', 'Value': eta_n})
    writer.writerow({'Name of Parameter': 'cos_phi', 'Value': cos_phi_n})
    writer.writerow({'Name of Parameter': 'p', 'Value': p})
    
    writer.writerow({'Name of Parameter': '', 'Value': ''})
  
    writer.writerow({'Name of Parameter': 'Sn', 'Value': Sn})
    writer.writerow({'Name of Parameter': 'I_1n', 'Value': I_1n})
    writer.writerow({'Name of Parameter': 'P_em', 'Value': P_em})
    writer.writerow({'Name of Parameter': 'ke', 'Value': ke})
    writer.writerow({'Name of Parameter': 'n1', 'Value': n1})
    writer.writerow({'Name of Parameter': 'D', 'Value': D})
    writer.writerow({'Name of Parameter': 'tau_p', 'Value': tau_p})
    writer.writerow({'Name of Parameter': 'B_delta', 'Value': B_delta})
    writer.writerow({'Name of Parameter': 'A', 'Value': A})
    writer.writerow({'Name of Parameter': 'q', 'Value': Z_stator / (2*p*m1)})   
    writer.writerow({'Name of Parameter': 'Z_stator', 'Value': Z_stator})
    writer.writerow({'Name of Parameter': 'Xi1', 'Value': Xi})
    writer.writerow({'Name of Parameter': 'y/tau_p', 'Value': CoilPitch})
    #writer.writerow({'Name of Parameter': 'kp', 'Value': 5})
    writer.writerow({'Name of Parameter': 'ky', 'Value': ky})  
    writer.writerow({'Name of Parameter': 'k_w1', 'Value': k_w1})
    writer.writerow({'Name of Parameter': 'l_delta', 'Value': l_delta})
    writer.writerow({'Name of Parameter': 'delta', 'Value': delta})
    writer.writerow({'Name of Parameter': 'Phi_delta', 'Value': Phi_delta})
    writer.writerow({'Name of Parameter': 'W1', 'Value': W1})   
    writer.writerow({'Name of Parameter': 'N_k1', 'Value': N_k1})
    writer.writerow({'Name of Parameter': 'g1', 'Value': g1})
    """
    writer.writerow({'Name of Parameter': 'n1', 'Value': n1})
    writer.writerow({'Name of Parameter': 'a1', 'Value': a1})
    """
    writer.writerow({'Name of Parameter': 'S_Cu1', 'Value': S_Cu1})    
    writer.writerow({'Name of Parameter': 'd', 'Value': d})   
    writer.writerow({'Name of Parameter': 'S1', 'Value': S1})
    writer.writerow({'Name of Parameter': 'k_Cu', 'Value': k_Cu})
    writer.writerow({'Name of Parameter': 'Sk', 'Value': Sk})
    writer.writerow({'Name of Parameter': 'n_k1', 'Value': n_k1})
    writer.writerow({'Name of Parameter': 'S_Cuk', 'Value': S_Cuk})  
    writer.writerow({'Name of Parameter': 't1', 'Value': t1})
    writer.writerow({'Name of Parameter': 'k_Fe', 'Value': k_Fe})
    writer.writerow({'Name of Parameter': 'B_z1', 'Value': B_z1})
    writer.writerow({'Name of Parameter': 'b_z1', 'Value': b_z1})
    writer.writerow({'Name of Parameter': 'a1', 'Value': a1})   
    writer.writerow({'Name of Parameter': 'h5', 'Value': h5})
    writer.writerow({'Name of Parameter': 'h6', 'Value': h6})
    writer.writerow({'Name of Parameter': 'b_k11', 'Value': b_k11})
    writer.writerow({'Name of Parameter': 'b_k21', 'Value': b_k21})
    writer.writerow({'Name of Parameter': 'h_z1', 'Value': h_z1})  
    writer.writerow({'Name of Parameter': 'h1', 'Value': h1})   
    writer.writerow({'Name of Parameter': 'D_k1', 'Value': D_k1})
    writer.writerow({'Name of Parameter': 'B_v1', 'Value': B_v1})
    writer.writerow({'Name of Parameter': 'h_v1', 'Value': h_v1})
    writer.writerow({'Name of Parameter': 'D_11', 'Value': D_11})
    
    writer.writerow({'Name of Parameter': '', 'Value': ''})    
    
    writer.writerow({'Name of Parameter': 'Z_rotor', 'Value': Z_rotor})  
    writer.writerow({'Name of Parameter': 'D2', 'Value': D2})
    writer.writerow({'Name of Parameter': 't2', 'Value': t2})
    writer.writerow({'Name of Parameter': 'k_i2', 'Value': k_i2})
    writer.writerow({'Name of Parameter': 'I2', 'Value': I2})
    writer.writerow({'Name of Parameter': 'Xi2', 'Value': Xi2})   
    writer.writerow({'Name of Parameter': 'Ip', 'Value': Ip})
    writer.writerow({'Name of Parameter': 'g2', 'Value': g2})
    writer.writerow({'Name of Parameter': 'S_Cu2', 'Value': S_Cu2})
    writer.writerow({'Name of Parameter': 'gp', 'Value': gp})
    writer.writerow({'Name of Parameter': 'Sp', 'Value': Sp})
    writer.writerow({'Name of Parameter': 'a2', 'Value': a2})   
    writer.writerow({'Name of Parameter': 'h_12', 'Value': h_12})
    writer.writerow({'Name of Parameter': 'h_42', 'Value': h_42})
    writer.writerow({'Name of Parameter': 'b_k2', 'Value': b_k2})
    writer.writerow({'Name of Parameter': 'h_z2', 'Value': h_z2})
    writer.writerow({'Name of Parameter': 'Sk', 'Value': Sk})  
    writer.writerow({'Name of Parameter': 'b_z2_max', 'Value': b_z2_max})
    writer.writerow({'Name of Parameter': 'b_z2_min', 'Value': b_z2_min})
    writer.writerow({'Name of Parameter': 'b_z2_avg', 'Value': b_z2_avg})
    
    writer.writerow({'Name of Parameter': 'hp', 'Value': hp})
    writer.writerow({'Name of Parameter': 'bp', 'Value': bp})   
    writer.writerow({'Name of Parameter': 'B_v2', 'Value': B_v2})
    writer.writerow({'Name of Parameter': 'h_v2', 'Value': h_v2})
    writer.writerow({'Name of Parameter': 'D22', 'Value': D_22})
    
    writer.writerow({'Name of Parameter': '', 'Value': ''})
 
    writer.writerow({'Name of Parameter': 'H_v1', 'Value': H_v1})
    writer.writerow({'Name of Parameter': 'l_v1', 'Value': l_v1}) 
    writer.writerow({'Name of Parameter': 'F_v1', 'Value': F_v1})
    writer.writerow({'Name of Parameter': 'H_z1', 'Value': H_z1})
    writer.writerow({'Name of Parameter': 'l_z1', 'Value': l_z1})
    writer.writerow({'Name of Parameter': 'F_z1', 'Value': F_z1})
    writer.writerow({'Name of Parameter': 'k_delta_1', 'Value': k_delta1})
    writer.writerow({'Name of Parameter': 'k_delta_2', 'Value': k_delta2})
    writer.writerow({'Name of Parameter': 'k_delta', 'Value': k_delta})
    writer.writerow({'Name of Parameter': 'H_delta', 'Value': H_delta})
    writer.writerow({'Name of Parameter': 'F_delta', 'Value': F_delta})
    """
    writer.writerow({'Name of Parameter': 'B_z2_max', 'Value': B_z2_max})
    writer.writerow({'Name of Parameter': 'B_z2_min', 'Value': B_z2_min})
    writer.writerow({'Name of Parameter': 'B_z2_avg', 'Value': B_z2_avg})
    """
    #writer.writerow({'Name of Parameter': 'H_z2_max', 'Value': H_z2_max})
    #writer.writerow({'Name of Parameter': 'H_z2_min', 'Value': H_z2_min})
    #writer.writerow({'Name of Parameter': 'H_z2_avg', 'Value': H_z2_avg})
    writer.writerow({'Name of Parameter': 'F_z2', 'Value': F_z2})
    writer.writerow({'Name of Parameter': 'l_v2', 'Value': l_v2})
    writer.writerow({'Name of Parameter': 'H_v2', 'Value': H_v2})
    writer.writerow({'Name of Parameter': 'F_v2', 'Value': F_v2})
    writer.writerow({'Name of Parameter': 'Fv', 'Value': Fv})
    
    writer.writerow({'Name of Parameter': 'I0_mif', 'Value': I0_mif})
    writer.writerow({'Name of Parameter': 'I0_mi[%]', 'Value': i0_mi_percentage})
    
    writer.writerow({'Name of Parameter': '', 'Value':''})
    
    writer.writerow({'Name of Parameter': 'l_avg', 'Value': l_sr1})
    writer.writerow({'Name of Parameter': 'L1', 'Value': L1})
    writer.writerow({'Name of Parameter': 'r1_15', 'Value': r1_15})
    writer.writerow({'Name of Parameter': 'r1_75', 'Value': r1_75})
    writer.writerow({'Name of Parameter': 'Dp', 'Value': Dp})
    writer.writerow({'Name of Parameter': 'r2_15', 'Value': r2_15})
    writer.writerow({'Name of Parameter': 'r2_75', 'Value': r2_75})
    writer.writerow({'Name of Parameter': 'k', 'Value': k})
    writer.writerow({'Name of Parameter': 'r2_75_prime', 'Value': r2_svedeno})
    writer.writerow({'Name of Parameter': 'lambda_k1', 'Value': lambda_k1})
    writer.writerow({'Name of Parameter': 'lambda_cv1', 'Value': lambda_cv1})
    writer.writerow({'Name of Parameter': 'lambda_d1', 'Value': lambda_d1})
    writer.writerow({'Name of Parameter': 'x1', 'Value': x_sigma1})
    writer.writerow({'Name of Parameter': 'lambda_k2', 'Value': lambda_k2})
    writer.writerow({'Name of Parameter': 'lambda_k2', 'Value': lambda_k2})
    writer.writerow({'Name of Parameter': 'lambda_cv2', 'Value': lambda_cv2})
    writer.writerow({'Name of Parameter': 'x2', 'Value': x_sigma2})
    writer.writerow({'Name of Parameter': 'x2_prime', 'Value': x_sigma2_svedeno})
    writer.writerow({'Name of Parameter': 'xm', 'Value': xm})
    writer.writerow({'Name of Parameter': 'rm', 'Value': rm})
    """
    writer.writerow({'Name of Parameter': '', 'Value': H_v1})
    writer.writerow({'Name of Parameter': 'H_v1', 'Value': H_v1})
    writer.writerow({'Name of Parameter': 'H_v1', 'Value': H_v1})
    writer.writerow({'Name of Parameter': 'H_v1', 'Value': H_v1})
    """

    writer.writerow({'Name of Parameter': 'P_Cu10', 'Value': P_Cu10})
    writer.writerow({'Name of Parameter': 'P_Cu_1n', 'Value': P_Cu_1n})
    writer.writerow({'Name of Parameter': 'P_Cu_2n', 'Value': P_Cu_2n})
    writer.writerow({'Name of Parameter': 'p_Fe_v1', 'Value': p_Fe_v1})
    writer.writerow({'Name of Parameter': 'm_Fe_v1', 'Value': m_Fe_v1})
    writer.writerow({'Name of Parameter': 'P_Fe_v1', 'Value': P_Fe_v1})
    writer.writerow({'Name of Parameter': 'p_Fe_z1', 'Value': p_Fe_z1})
    writer.writerow({'Name of Parameter': 'm_Fe_z1', 'Value': m_Fe_z1})
    writer.writerow({'Name of Parameter': 'P_Fe_z1', 'Value': P_Fe_z1})
    writer.writerow({'Name of Parameter': 'P_Fe', 'Value': P_Fe})
    writer.writerow({'Name of Parameter': 'P0', 'Value': P0})

    writer.writerow({'Name of Parameter': 'sigma_1', 'Value': sigma_1})
    writer.writerow({'Name of Parameter': 'R1', 'Value': R1})
    writer.writerow({'Name of Parameter': 'X1', 'Value': X1})
    writer.writerow({'Name of Parameter': 'R2', 'Value': R2})
    writer.writerow({'Name of Parameter': 'X2', 'Value': X2})
    writer.writerow({'Name of Parameter': 'I00', 'Value': I00})
    writer.writerow({'Name of Parameter': 'cos_phi00', 'Value': cos_phi00})
    writer.writerow({'Name of Parameter': 'Xk', 'Value': Xk})    

import csv_write_mechanical

